<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqRepository extends EntityRepository
{
    public function findAllActive()
    {
        $qb = $this->createQueryBuilder('f');
        $qb
            ->where($qb->expr()->eq('f.isActive', $qb->expr()->literal(true)));

        return $qb->getQuery()->getResult();
    }
}
