services:
    ####################################################################################################################
    #  E V E N T   L I S T E N E R
    ####################################################################################################################
    app_bundle.contact.listener:
        class: AppBundle\Listener\ContactListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@templating.engine.twig"
            - "@mailer"
            - "@translator"
        tags:
            - { name: kernel.event_listener, event: contact.event.created, method: onContactCreatedEvent }
