services:
  _defaults:
    autowire: true
    autoconfigure: true

  ######################################################################################################################
  #  E V E N T   L I S T E N E R
  ######################################################################################################################
  AppBundle\Listener\ContactListener: ~

  ######################################################################################################################
  #  T W I G   E X T E N S I O N S
  ######################################################################################################################
  AppBundle\Twig\EmailObfuscatorExtension: ~
